name: Test Llama End to End

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - refactor-stateless_llama.py

jobs:
  test:
    strategy:
      matrix:
        version: [3.11]
        os: [xida-cpu-0]

    runs-on: ${{matrix.os}}
    steps:
      - name: "Setting up Python"
        uses: actions/setup-python@75f3110429a8c05be0e1bf360334e4cced2b63fa # v2.3.3
        with:
          python-version: ${{matrix.version}}

      - name: "Checkout Code"
        uses: actions/checkout@v2

      - name: Sync source deps
        run: |
          python -m pip install --upgrade pip
          # Note: We install in three steps in order to satisfy requirements
          # from non default locations first. Installing the PyTorch CPU
          # wheels saves multiple minutes and a lot of bandwidth on runner setup.
          pip install --index-url https://download.pytorch.org/whl/cpu \
            -r pytorch-cpu-requirements.txt \
            -r torchvision-requirements.txt          
          pip install --upgrade -r requirements.txt
          pip install -e  .[testing]

      - name: Run tests
        run: |
          pytest tests/custom_models/stateless_llama
